// Generated 09 Nov 2021 16:21 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Maintenance
{
    [Serializable]
    public class ProductList
     : SingularBusinessListBase<ProductList, Product>
    {
        #region " Business Methods "

        public Product GetItem(int ProductID)
        {
            foreach (Product child in this)
            {
                if (child.ProductID == ProductID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Products";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public int? CategoryID { get; set; }
            public int? ProductID { get; set; }
            public bool IsActiveInd { get; set; }
            public Criteria()
            {
            }

            public Criteria(int CategoryID, int ProductID, bool IsActiveInd)
            {
                this.CategoryID = CategoryID;
                this.ProductID = ProductID;
                this.IsActiveInd = IsActiveInd;
            }

        }

        public static ProductList NewProductList()
        {
            return new ProductList();
        }

        public ProductList()
        {
            // must have parameter-less constructor
        }

        public static ProductList GetProductList()
        {
            return DataPortal.Fetch<ProductList>(new Criteria());
        }
        public static ProductList GetProductList(int? CategoryID, int? ProductID)
        {
            return DataPortal.Fetch<ProductList>(new Criteria() { CategoryID = CategoryID, ProductID = ProductID });
        }
        public static ProductList GetProductList(bool IsActiveInd)
        {
            return DataPortal.Fetch<ProductList>(new Criteria() { IsActiveInd = IsActiveInd });
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Product.GetProduct(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getProductList";
                        cm.Parameters.AddWithValue("@CategoryID", Singular.Misc.ZeroDBNull(crit.CategoryID));
                        cm.Parameters.AddWithValue("@ProductID", Singular.Misc.ZeroDBNull(crit.ProductID));
                        cm.Parameters.AddWithValue("@IsActiveInd", Singular.Misc.ZeroDBNull(crit.IsActiveInd));
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}