// Generated 20 Oct 2021 13:45 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Maintenance
{
    [Serializable]
    public class SupplierList
     : SingularBusinessListBase<SupplierList, Supplier>
    {
        #region " Business Methods "

        public Supplier GetItem(int SupplierID)
        {
            foreach (Supplier child in this)
            {
                if (child.SupplierID == SupplierID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Suppliers";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static SupplierList NewSupplierList()
        {
            return new SupplierList();
        }

        public SupplierList()
        {
            // must have parameter-less constructor
        }

        public static SupplierList GetSupplierList()
        {
            return DataPortal.Fetch<SupplierList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Supplier.GetSupplier(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getSupplierList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}