// Generated 28 Oct 2021 16:00 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Basket
{
    [Serializable]
    public class BasketEntryList
     : SingularBusinessListBase<BasketEntryList, BasketEntry>
    {
        #region " Business Methods "

        public BasketEntry GetItem(int BasketEntryID)
        {
            foreach (BasketEntry child in this)
            {
                if (child.BasketEntryID == BasketEntryID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Basket Entrys";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }
            public int? UserID { get; set; }
            public int? ProductID { get; set; }
        }

        public static BasketEntryList NewBasketEntryList()
        {
            return new BasketEntryList();
        }

        public BasketEntryList()
        {
            // must have parameter-less constructor
        }

        public static BasketEntryList GetBasketEntryList()
        {
            return DataPortal.Fetch<BasketEntryList>(new Criteria());
        }
        public static BasketEntryList GetBasketEntryList(int UserID)
        {
            return DataPortal.Fetch<BasketEntryList>(new Criteria() { UserID = UserID});
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(BasketEntry.GetBasketEntry(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getBasketEntryList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}