// Generated 12 Nov 2021 13:53 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Basket
{
    [Serializable]
    public class DeliveryOptionList
     : SingularBusinessListBase<DeliveryOptionList, DeliveryOption>
    {
        #region " Business Methods "

        public DeliveryOption GetItem(int DeliveryOptionID)
        {
            foreach (DeliveryOption child in this)
            {
                if (child.DeliveryOptionID == DeliveryOptionID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Delivery Options";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static DeliveryOptionList NewDeliveryOptionList()
        {
            return new DeliveryOptionList();
        }

        public DeliveryOptionList()
        {
            // must have parameter-less constructor
        }

        public static DeliveryOptionList GetDeliveryOptionList()
        {
            return DataPortal.Fetch<DeliveryOptionList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(DeliveryOption.GetDeliveryOption(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getDeliveryOptionList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}