// Generated 25 Oct 2021 14:08 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Accounts
{
    [Serializable]
    public class WalletList
     : SingularBusinessListBase<WalletList, Wallet>
    {
        #region " Business Methods "

        public Wallet GetItem(int WalletID)
        {
            foreach (Wallet child in this)
            {
                if (child.WalletID == WalletID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Wallets";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static WalletList NewWalletList()
        {
            return new WalletList();
        }

        public WalletList()
        {
            // must have parameter-less constructor
        }

        public static WalletList GetWalletList()
        {
            return DataPortal.Fetch<WalletList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Wallet.GetWallet(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getWalletList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}